### ISSUE TITLE
项目编译出错

### ISSUE THREAD

**Issue by luchuantao** [AgoraIO/OpenVideoCall-Android#2]
你好，下面是项目编译时出现的错误信息。麻烦有时间 帮忙看下，谢谢！

error：

Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources]
Error:Some file crunching failed, see logs for details
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: Some file crunching failed, see logs for details
Information:BUILD FAILED
Information:Total time: 4.023 secs
Information:2 errors
Information:0 warnings
Information:See complete output in console

**Comment by guohai** [comment]
能有详细点的信息么？这是  Windows 上的？

**Comment by ZhanRu** [comment]
E:\Work_Source\Agora\OpenVideoCall-Android-master\app\src\main\cpp\video_preprocessing_plugin_jni.cpp
Error:(5, 10) fatal error: 'agora/IAgoraRtcEngine.h' file not found

**Comment by vikashign** [comment]
How to solve this error?
C:\Users\vikashign\Desktop\agora\AdvanceVideoCall\app\src\main\cpp\video_preprocessing_plugin_jni.cpp
Error:(5, 10) fatal error: 'agora/IAgoraRtcEngine.h' file not found

**Comment by haoxingren9999** [comment]
How to solve this error?
C:\Users\vikashign\Desktop\agora\AdvanceVideoCall\app\src\main\cpp\video_preprocessing_plugin_jni.cpp
Error:(5, 10) fatal error: 'agora/IAgoraRtcEngine.h' file not found   有人解决吗？

**Comment by MonsterDonkey** [comment]
找到.h文件并放在指定的位置

**Comment by guohai** [comment]
for issue Error:(5, 10) fatal error: 'agora/IAgoraRtcEngine.h' file not found

copy header files into folder **app/src/main/cpp/agora**
