### ISSUE TITLE
io.agora.rtc.* 包找不到

### ISSUE THREAD

**Issue by wx962464** [AgoraIO/OpenVideoCall-Android#5]
编译一直找不到io.agora.rtc.*下的相关类

**Comment by guohai** [comment]
参见 README

运行示例程序

首先在 Agora.io 注册 注册账号，并创建自己的测试项目，获取到 AppID。将 AppID 填写进 "app/src/main/res/values/strings_config.xml"

<string name="private_app_id"><#YOUR APP ID#></string>
然后在 Agora.io SDK 下载 视频通话 + 直播 SDK，解压后将其中的 libs 文件夹下的 *.jar 复制到本项目的 app/libs 下，其中的 libs 文件夹下的 arm64-v8a/x86/armeabi-v7a 复制到本项目的 app/src/main/libs 下，其中的 libs/include 文件夹下的 IAgoraMediaEngine.h/IAgoraRtcEngine.h 复制到本项目的 app/src/main/cpp/agora 下。

最后用 Android Studio 打开该项目，连上设备，编译并运行。

也可以使用 Gradle 直接编译运行。
